# Generated by Django 5.0.14 on 2025-05-16 16:51
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_remove_comment_tags_post_tags"),
    ]

    operations = [
        TrigramExtension(),
    ]
